### ISSUE TITLE
No Recognition happening

### ISSUE THREAD

**Issue by chandraOloid** [gv22ga/dlib-face-recognition-android#25]
Hi @gv22ga @gauravgupta22 
 I am using Samsung galaxy s8+ and am not getting any recognition.

 File[https://drive.google.com/open?id=1L6-ny5tn94_BA-ypr5yge0C3zqZRy35e]

 Here is a sample screenshot of the same. 

 Please let me know how I can fix this. 

Thanks
Chandra

**Comment by amolrajput1** [comment]
Same issue I am facing, at the time of adding person face detected but at the time of recognition face not detected.

**Comment by cahyo0118** [comment]
You must rotate the taken image to 270 degree
