### ISSUE TITLE
Exact Landmark Position on Facerecogniton

### ISSUE THREAD

**Issue by okankrblt** [gv22ga/dlib-face-recognition-android#3]
How can i get exact pixel positions in the picture. What should i add the code ?
i only interests with FaceRecognition part so i need to find the landmark's pixel positions.

**Comment by gv22ga** [comment]
Sorry, I couldn't understand what you are saying. 

Do you want to get the bounding box for the face of a recognized person?
You can get coordinates of bounding box by 
`getTop(), getLeft(), getBottom(), getRight()` methods of `VisionDetRet`

If you want to get face landmark positions (locations of eye, nose etc) then you can look into this project
[dlib android app](https://github.com/tzutalin/dlib-android-app)
