### ISSUE TITLE
Can you submit other ABI than arm64-v8a please? armeabi-v7a, x86, x86_64

### ISSUE THREAD

**Issue by AntonioVitiello** [gv22ga/dlib-face-recognition-android#6]
Hi Gaurav, thank you for sharing your great value project!
I'am a Java developer, don't know how to compile C++ to obtain all libandroid_dlib.so files.
Can you please submit other ABI than arm64-v8a? I mean armeabi-v7a, x86, x86_64
Thank you

**Comment by gv22ga** [comment]
Hi Vitiello,

sorry for the late reply

I have updated the code to work with other ABIs

**Comment by AntonioVitiello** [comment]
Many thanks Gaurav you were really very kind!
Greetings,
Antonio.
